Repository playground-vue/TIL-Project, pull requests merged in 2023-02, with the labels that each got.

#18 BaseTitleSkelton 컴포넌트 개발
  .storybook/preview-head.html
  src/components/baseTitle/BaseTitle.stories.ts
  src/components/baseTitle/BaseTitleSkeleton.vue
  src/main.ts
  src/styles/animation.scss
  src/styles/base.scss
Labels: feature, storybook

#22 feat: remove storybook file, warning log
  src/components/baseDropdown/BaseDropdown.stories.ts
  src/components/baseFooter/BaseFooter.stories.ts
  src/components/baseHeader/BaseHeader.stories.ts
  src/components/baseInput/BaseInput.stories.ts
  src/components/baseNav/BaseNav.stories.ts
Labels: storybook, fix

#24 BestSellerOfMonthBox 컴포넌트 개발
  db.json
  package-lock.json
  package.json
  src/components/cardText/CardText.stories.ts
  src/components/cardText/CardText.vue
  src/components/cardText/types.ts
  src/components/containers/bestSellerOfMonthBox/BestSellerOfMonthBox.vue
  src/components/containers/bestSellerOfMonthBox/BestSellerOfMonthBoxSkeleton.vue
  src/components/containers/bestSellerOfMonthBox/uses.ts
  src/services/bestSellerService.ts
  src/services/index.ts
  src/styles/base.scss
  src/views/ECommerceView.vue
Labels: feature

#25 feat: vite-plugin-vue-type-imports 설치 및 코드적용
  package-lock.json
  package.json
  src/components/TheWelcome.vue
  src/components/WelcomeItem.vue
  src/components/baseButton/BaseButton.vue
  src/components/baseButton/uses.ts
  src/components/baseDropdown/BaseDropdown.vue
  src/components/baseDropdown/uses.ts
  src/components/baseHeader/BaseHeader.vue
  src/components/baseInput/BaseInput.stories.ts
  src/components/baseInput/BaseInput.vue
  src/components/baseInput/uses.ts
  src/components/baseNav/BaseNav.vue
  src/components/baseNavItem/BaseNavItem.stories.ts
  src/components/baseSelect/BaseSelect.stories.ts
  src/components/baseSelect/BaseSelect.vue
  src/components/baseSelect/types.ts
  src/components/baseSelect/uses.ts
  src/components/baseTitle/BaseTitle.stories.ts
  src/components/baseTitle/BaseTitle.vue
  src/components/buttonIcon/ButtonIcon.stories.ts
  src/components/buttonIcon/ButtonIcon.vue
  src/components/buttonIcon/uses.ts
  src/components/cardText/CardText.stories.ts
  src/components/cardText/CardText.vue
  src/components/cardText/CardTextSkeleton.vue
  src/components/cardText/uses.ts
  src/components/icons/IconCommunity.vue
  src/components/icons/IconDocumentation.vue
  src/components/icons/IconEcosystem.vue
  src/components/icons/IconSupport.vue
  src/components/icons/IconTooling.vue
  src/views/DashboardViewport.vue
  src/views/LoginView.vue
  vite.config.ts
Labels: feature, refactor

#29 feat: BaseNav의 메뉴 리스트 렌더링, active 처리, 코드 리펙토링
  src/common/utils.ts
  src/components/baseNav/BaseNav.vue
  src/components/baseNav/uses.ts
  src/components/baseNavItem/BaseNavItem.vue
Labels: feature, refactor

#31 CardAddBox 컴포넌트 개발
  .storybook/main.cjs
  env.d.ts
  src/assets/icon-plus.svg
  src/assets/icon-todo.svg
  src/components/baseDropdown/BaseDropdown.vue
  src/components/baseDropdown/uses.ts
  src/components/baseNav/uses.ts
  src/components/baseSelect/BaseSelect.stories.ts
  src/components/baseSelect/BaseSelect.vue
  src/components/cardAddBox/CardAddBox.vue
  src/router/index.ts
  src/views/TodoView.vue
Labels: feature
