Repository playground-vue/TIL-Project, pull requests merged in 2023-01, with the labels that each got.

#3 feat: BaseInput 컴포넌트 개발
  src/components/baseInput/BaseInput.stories.ts
  src/components/baseInput/BaseInput.vue
  src/components/baseInput/uses.ts
Labels: feature, storybook

#4 feat: Base Select 컴포넌트 개발
  package-lock.json
  package.json
  src/components/baseDropdown/BaseDropdown.vue
  src/components/baseSelect/BaseSelect.stories.ts
  src/components/baseSelect/BaseSelect.vue
  src/components/baseSelect/types.ts
Labels: feature, storybook

#6 feat: Header 영역 내 아이콘 추가 (vite-svg-loader 설치)
  package-lock.json
  package.json
  src/assets/icon-alarm.svg
  src/assets/icon-frame.svg
  src/assets/icon-language.svg
  src/assets/icon-menu.svg
  src/assets/icon-search.svg
  src/assets/icon-theme.svg
  src/components/baseCard/BaseCard.vue
  src/components/baseHeader/BaseHeader.vue
  src/components/buttonIcon/ButtonIcon.vue
  vite.config.ts
Labels: feature

#7 feat: BaseInput 컴포넌트 웹 접근성 추가
  src/common/utils.ts
  src/components/baseInput/BaseInput.vue
  src/components/baseInput/uses.ts
Labels: feature, storybook

#11 refactor: Base Select 컴포넌트 리팩터링
  src/components/baseSelect/BaseSelect.stories.ts
  src/components/baseSelect/BaseSelect.vue
Labels: refactor
